server:
  jetty:
    accesslog:
      append: true
      enabled: true
  port: 8080
spring:
  application:
    name: ${app.name}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/spring_boot_sample?rewriteBatchedStatements=true
    username: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
        generate_statistics: true

  ##Feign Client
  cloud:
    openfeign:
      client:
        config:
          rick-and-morty:
            url: https://rickandmortyapi.com/api
            connectTimeout: 3000
            readTimeout: 5000
          http-bin:
            url: https://httpbin.org
            connectTimeout: 3000
            readTimeout: 5000

    #Kafka Configs
    kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

  #Redis Configuration
  cache:
    type: redis
    cache-names: rick
  data:
    redis:
      host: localhost
      port: 6379

app:
  cache:
    redis:
      enabled: true
      host: localhost
      port: 6379

#management:
#  security:
#    enabled: false

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

logging:
  config: classpath:logback.xml

management:
  tracing:
    enabled: true
  sampling:
    probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  observations:
    annotations:
      enabled: true

